language: java

jdk:
  - oraclejdk8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9d082586e459ec0fb134
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

deploy:

  - provider: script
    skip_cleanup: true
    script: .travis/znode-deploy.sh
    on:
      branch: master

  - provider: releases
    skip_cleanup: true
    api_key:
      secure: GqBVV6OCdr6n6KSaq14X+2f2+I1mTwPqpQ7L6sdPUZUD/ziXA4rySZ9R3MYYxZWo/SOvAzX5ab8QpJSGnPoXZncL7dxFmO3FfE0WMHy74FCinuRWQ2ziBK4TEJBOVGfJqTvyutmCXLniw5G8uQxozkEUpjKJm3i1bjA+7X+7qlI=
    file_glob: true
    file: target/Gringotts*.jar
    on:
      repo: MinecraftWars/Gringotts
      tags: true

# we don't need sudo, this allows container-based builds ...
sudo: false

# ... which allows caching of .m2 and makes builds faster
cache:
  directories:
  - $HOME/.m2
